### PR TITLE
Updated NLog and created build profile for any cpu

### PR DESCRIPTION
**Pull request by TRex22**

### CODE REVIEW

**Comment by TRex22** [comment]
Please could you check what your automated checks are. It turns out I had to recreate the whole project due to it breaking our build.

**Comment by tiernano** [comment]
looks like nLog is not being pulled in... I will checkout the code and see whats going on... bit busy at the moment... give me a few hours...

**Comment by tiernano** [comment]
right... after a bit of digging, it seems the files in the .nuget folder (nuget.exe, etc) need to be included in the checkin... in VS, there should be an option when you right click on the project about package restoring... if you select that, it should add back the .nuget folder. add that folder in your check in. it should the compile... once compiled, i will merge...

**Comment by TRex22** [comment]
ok will do. Unfortunately Im back at university and my pc died. So I will first have to install VS

**Comment by tiernano** [comment]
going to close this because #5 already sorts this out.

**Pull request closed without merging**
