### PR TITLE
Some minor changes

### PR DESCRIPTION
**Pull request by janohl**
Changed default buffer size to 1 and shouldBuffer to false. 
Upgraded NLog to 3.2.0.0.
Added build configuration for x64 and 'AnyCpu'

### CODE REVIEW

**Comment by tiernano** [comment]
will do a build and deploy to nuget later today. Thanks again!

**Comment by chos** [comment]
Hi! I was looking at nuget for this latest patch but couldn't find it. Have you published the new package yet? Will this new package use the x64 configuration?

**Comment by tiernano** [comment]
Have not had a chance to push to Nuget just yet. Hope to do this in the next day or two.

--Tiernan




On Tue, Jun 2, 2015 at 6:39 AM -0700, "Christofer Österberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi! I was looking at nuget for this latest patch but couldn't find it. Have you published the new package yet? Will this new package use the x64 configuration?

-

**Comment by chos** [comment]
OK, great!

**Comment by tiernano** [comment]
this is now built and on nuget. There are 2 seperate packages available: 

https://www.nuget.org/packages/LogglyTarget.x64/

https://www.nuget.org/packages/LogglyTarget

Thanks again!

--Tiernan

**Comment by chos** [comment]
Thank you, that's super!

**Pull request merged**
